server:
  port: ":8280"
mongo:
  uri: "mongodb://localhost:27017"
  database: "oms"
  collection: "orders"
sqs:
  name: "First"
  workerCount: 1
  region: "eu-north-1"
  endpoint: "https://sqs.eu-north-1.amazonaws.com/061039762751/First"
  account: "061039762751"
  concurrencyPerWorker: 1
